# Generated by Django 3.2.12 on 2022-02-17 10:10

import django.core.validators
from django.db import migrations, models
import djangoProject1.web.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expense_image', models.URLField()),
                ('price', models.FloatField(validators=[djangoProject1.web.custom_validators.validate_positive_number])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), djangoProject1.web.custom_validators.validate_only_letter])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), djangoProject1.web.custom_validators.validate_only_letter])),
                ('budget', models.FloatField(default=0)),
                ('profile_image', models.ImageField(upload_to='', validators=[djangoProject1.web.custom_validators.ValidateImageMaxSizeInMb(5)])),
            ],
        ),
    ]
