# Generated by Django 3.2.12 on 2022-02-17 11:47

from django.db import migrations, models
import djangoProject1.web.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[djangoProject1.web.custom_validators.ValidateImageMaxSizeInMb(5)]),
        ),
    ]
