# Generated by Django 3.2.12 on 2022-02-20 10:14

import django.core.validators
from django.db import migrations, models
import djangoProject1.web.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), djangoProject1.web.custom_validators.validate_only_letter], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), djangoProject1.web.custom_validators.validate_only_letter], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[djangoProject1.web.custom_validators.ValidateImageMaxSizeInMb(5)], verbose_name='Profile Image'),
        ),
    ]
