# Generated by Django 3.2.12 on 2022-03-15 13:23

import common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pet Name')),
                ('type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog'), ('bunny', 'bunny'), ('parrot', 'parrot'), ('fish', 'fish'), ('other', 'other')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), common.validators.validate_only_letters], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), common.validators.validate_only_letters], verbose_name='Last Name')),
                ('profile_picture', models.URLField(verbose_name='Link to Profile Picture')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('description', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[common.validators.MaxFileSizeInMbValidator(5)], verbose_name='Pet Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='main_app.Pet', verbose_name='Tag Pets')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('user_profile', 'name')},
        ),
    ]
