# Generated by Django 3.2.12 on 2022-03-16 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_pet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Tag Pets'),
        ),
    ]
