# Generated by Django 3.2.12 on 2022-03-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220316_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='user',
        ),
    ]
