# Generated by Django 3.2.12 on 2022-03-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
