# Generated by Django 3.2.12 on 2022-03-05 10:08

import Petstagram.main.validators_custom
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220223_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[Petstagram.main.validators_custom.validate_date_not_in_future], verbose_name='Day of Birth'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user_profile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AlterField(
            model_name='petsphoto',
            name='photo',
            field=models.FileField(upload_to='media/', validators=[Petstagram.main.validators_custom.ValidatePhotoMaxSizeMb(5)], verbose_name='Pet Image'),
        ),
        migrations.AlterField(
            model_name='petsphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to='main.Pet', verbose_name='Tag Pets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[Petstagram.main.validators_custom.validate_date_not_in_future]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Petstagram.main.validators_custom.validate_only_letters], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Petstagram.main.validators_custom.validate_only_letters], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(verbose_name='Link to Profile Picture'),
        ),
    ]
