# Generated by Django 3.2.12 on 2022-03-05 10:16

import Petstagram.main.validators_custom
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_petsphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsphoto',
            name='photo',
            field=models.ImageField(upload_to='images/', validators=[Petstagram.main.validators_custom.ValidatePhotoMaxSizeMb(5)], verbose_name='Pet Image'),
        ),
    ]
