# Generated by Django 3.2.12 on 2022-03-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_petsphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petsphoto',
            options={'ordering': ('id', 'date_and_time_of_publication')},
        ),
    ]
