# Generated by Django 3.2.12 on 2022-03-05 13:14

import Petstagram.main.validators_custom
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_petsphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='user_profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[Petstagram.main.validators_custom.validate_date_not_in_future], verbose_name='Date of Birth'),
        ),
    ]
